config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :beer_clubs
  resources :users do
    post 'close', on: :member
    post 'open', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  
  resources :memberships
  
  get '/', to: 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'

  resources :ratings, only: [:index, :new, :create, :destroy]
  #get 'ratings', to: 'ratings#index'
  #get 'ratings/new', to:'ratings#new'
  #post 'ratings', to: 'ratings#create'
  
  resource :session, only: [:new, :create, :destroy]
  ##get 'session', to: 'session#index'
  #get 'sessions/new', to:'sessions#new'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  
  resources :places, only: [:index, :show]
  # get 'places', to:'places#index'
  # get 'places/:id', to:'places#show'

  post 'places', to:'places#search'

  get 'beerlist', to:'beers#list'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  include RatingAverage
  extend Top

  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships
  has_secure_password

  validates :username, uniqueness: true, length: { minimum: 3, maximum: 30 }
  validates :password, length: { minimum: 4 }, format: { with: /(?=.*[A-Z])(?=.*[0-9]).*/ }

  def favorite_beer
    return nil if ratings.empty?

    ratings.order(score: :desc).limit(1).first.beer
  end

  def average_of(ratings)
    ratings.sum(&:score).to_f / ratings.count
  end

  def favorite_style
    return nil if ratings.empty?

    style_ratings = ratings.group_by{ |r| r.beer.style }
    averages = style_ratings.map do |style, ratings|
      { style: style, score: average_of(ratings) }
    end

    averages.max_by{ |r| r[:score] }[:style]
  end

  def favorite_brewery
    return nil if ratings.empty?

    beer_ratings = ratings.group_by{ |r| r.beer.brewery }
    averages = beer_ratings.map do |brewery, ratings|
      { brewery: brewery, score: average_of(ratings) }
    end

    averages.max_by{ |r| r[:score] }[:brewery]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.closed = false
    @user.admin = false

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? && @user == current_user && @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user != current_user
      redirect_to user_path(@user)
    else
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def open
    @user = User.find(params[:id])
    @user.update_attribute(:closed, false) if current_user.admin && @user != current_user
    redirect_to user_path(@user), notice: "Account has been opened"
  end

  def close
    @user = User.find(params[:id])
    @user.update_attribute(:closed, true) if current_user.admin && @user != current_user
    redirect_to user_path(@user), notice: "Account has been closed"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :admin, :closed)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div class="field">
      <%= form.label :username %>
      <%= form.text_field :username %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :password %><br />
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %><br />
    <%= form.password_field :password_confirmation  %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password for <%= current_user.username %></h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td>
          <% if !current_user.nil? && current_user.admin && user.closed %>
            <span class="badge badge-primary">account closed</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if not current_user.nil? %>
  <%= (link_to 'New User', new_user_path, class:'btn btn-primary') %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h2>
  <strong><%= @user.username %>
    <% if @user.closed %>
      <span class="badge badge-primary">account closed</span>
    <% end %>
  </strong>
</h2>

<% if !current_user.nil? && current_user.admin && current_user != @user %>
  <p>
    <% if @user.closed %>
      <%= (link_to 'Open account', open_user_path(@user), method: :post, data: { confirm: 'Open this account?' }, class: "btn btn-danger") %>
    <% else %>
      <%= (link_to 'Close account', close_user_path(@user), method: :post, data: { confirm: 'Close this account?' }, class: "btn btn-danger") %>
    <% end %>
  </p>
<% end %>


<p>
  <% if @user.ratings.empty? %>
    User has not done any ratings yet!
  <% else %>
    <p>Has made <%= pluralize(@user.ratings.count, 'rating', 'ratings')%>, average rating <%= @user.average_rating%></p>
    <p>Favorite beer: <%= @user.favorite_beer.name %></p>
    <p>Favorite brewery: <%= @user.favorite_brewery.name %></p>
    <p>Preferred style: <%= @user.favorite_style.name %></p>
  <% end %>
</p>

<p>
  
  <% if @user.memberships.empty? %>
    Not a member of any clubs.
  <% else %>
    Member of
    <ul>
      <% @user.memberships.each do |membership| %>
        <li>
          <%= link_to membership.beer_club.name, beer_club_path(membership.beer_club) %>
        </li>
      <% end %>
    </ul>
  <% end %>
</p>

<h3>
  <strong> ratings </strong>
</h3>

<ul>
  <% @user.ratings.each do |rating| %>
    <li>
      <%= rating %>
      <% if @user == current_user %>
          <%= link_to 'delete', rating, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </li>
  <% end %>
</ul>

<% if @user == current_user %>
  <%= edit_and_destroy_buttons(@user) %>
<% end %>